site_name: Lab 2, Authorization & Trust
repo_url: https://github.com/15316-cmu/lab2-2023

theme:
  name: material
  icon:
    logo: material/security-network
    favicon: material/security-network

nav:
  - 'index.md'
  - 'starter.md'
  - 'implementation.md'
  - 'auth.md'
  - 'tactics.md'
  - 'exploit.md'
  - 'utility.md'